### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by reedy** [makinacorpus/php-bloom#1]
Hey

I notice there's no licensing on this repo... Please license it? :)

**Comment by pounard** [comment]
Hello, which usage are you targeting ? Someone forwarded me a mail it was for a usage in another piece of software. I'm still undecided between MIT or GPL-2 or GPL-3, if that's for free software integration, just tell me which would be the best licence of those for your usage.

**Comment by reedy** [comment]
I was the one that emailed too.

It's potentially for reuse in other software (MediaWiki in this case), yeah. But it will be brought in via composer into a vendor repo, rather than just reusing the files directly.

I'm not so fussed about what actual licence to use. Any of those are fine by me/for this purpose. And is generally better than no licence at all

**Comment by pounard** [comment]
Ok, fine by me, I'll licence it within the week, I'm going for MIT I think, mostly because lots of PHP community projects seems to go along that road.

**Comment by reedy** [comment]
Thanks! Can you tag a new release after you have done it? 👍

**Comment by pounard** [comment]
Yes, it's planned.

**Comment by pounard** [comment]
It's now licensed with MIT, the new 2.0.2 release is up and propagated to packagist, have fun with it ! Do not hesitate, at any moment, asking any questions or propose fixes.
