### ISSUE TITLE
Doesn't work correctly on HHVM

### ISSUE THREAD

**Issue by reedy** [makinacorpus/php-bloom#5]
When running under PHPUnit as a validation of the bloom filter, we get the error message

```
00:53:59 Object of class GMP could not be converted to int
00:53:59 
00:53:59 /home/jenkins/workspace/composer-package-hhvm-jessie/vendor/makinacorpus/php-bloom/BloomFilter.php:100
00:53:59 /home/jenkins/workspace/composer-package-hhvm-jessie/vendor/makinacorpus/php-bloom/BloomFilter.php:149
00:53:59 /home/jenkins/workspace/composer-package-hhvm-jessie/src/PasswordBlacklist.php:28
00:53:59 /home/jenkins/workspace/composer-package-hhvm-jessie/tests/PasswordBlacklistTest.php:34
00:53:59 
```

And similarly, when trying to create a filter under hhvm, we get the same error...

```
Notice: Object of class GMP could not be converted to int in /home/reedy/PasswordBlacklist/vendor/makinacorpus/php-bloom/BloomFilter.php on line 100
```

**Comment by pounard** [comment]
Hum this is weird. FYI HHVM is not an targeted runtime, if it works with it, fine, if the patches to make it works are easy enough, fine, but if it just doesn't work, I won't fix myself.

**Comment by pounard** [comment]
It seems there hasn't been any demand or help provided for this, I'm closing this issue, HHVM has never been a target.
